apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a9f6lcjao-go 
  janus-idp.io/tekton: a9f6lcjao-go
  backstage.io/kubernetes-id: a9f6lcjao-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a9f6lcjao-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  